import type { Metadata } from "next";
import Home from "@/app/components/H/Home";
import React from "react";

export const metadata: Metadata = {
  title: "Home || Rise",
  description: "Generated by rise",
};

const HomePage = () => {
  return (
    <>
      <Home />
    </>
  );
};

export default HomePage;
